#detector main volume parameters
/NuSD/geometry/numberOfSegmentAlongX 7 #7
/NuSD/geometry/numberOfSegmentAlongY 7 #7
/NuSD/geometry/numberOfSegmentAlongZ 1 #1

/NuSD/geometry/neutrinoScntDimensions 12.7 12.7 120 cm # 12.7 12.7 120 cm

/NuSD/geometry/neutronScntThickness 0.32 mm #0.32 mm
/NuSD/geometry/optBarrierThickness 0.3 mm #0.3 mm
/NuSD/geometry/reflectorThickness 0.25 mm #0.25 mm

/NuSD/geometry/isOpticalReadoutOn true
 
#detector optical surface parameters 
/NuSD/geometry/opticalReadOut/isAttachedBothEnd true

#photoSensorBinder
/NuSD/geometry/opticalReadOut/isPSBinderOn false #false
/NuSD/geometry/opticalReadOut/psBinderLength 1 mm #1 mm

/NuSD/geometry/opticalReadOut/photoCathodeRadius 6.35 cm # 5inch-12.7 cm diameters pmts

/NuSD/geometry/opticalReadOut/isLightGuideOn false
/NuSD/geometry/opticalReadOut/lightGuideLength 4 cm

/NuSD/geometry/opticalReadOut/lightGuidePmtEndDimension 2 3 1 cm
/NuSD/geometry/opticalReadOut/isLgBinderOn false
/NuSD/geometry/opticalReadOut/lgBinderLength 1 mm #1mm

#reflector surface 
/NuSD/geometry/surface/reflector/isReflectivityDependsEnergy false #if it is true, the command below will be refused.
/NuSD/geometry/surface/reflector/reflectivity 0.96 #fixed value for all photon energies.

#photoSensor surface
/NuSD/geometry/surface/photoCathode/isQuantumEfficiencyDependsEnergy false #if it is true, the command below will be refused.
/NuSD/geometry/surface/photoCathode/quantumEfficiency 0.25  #fixed value for all photon energies.


# Initialize kernel
/run/initialize
#/control/execute macros/genericPrimary.mac




